# Generated by Django 6.0 on 2026-01-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isPrebaked',
            field=models.BooleanField(default=False),
        ),
    ]
