# Generated by Django 6.0 on 2026-01-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_isprebaked'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productType',
            field=models.CharField(choices=[('PREBAKED', 'Pre-baked'), ('READY_TO_BAKE', 'Ready-to-bake')], default='PREBAKED', max_length=20),
        ),
    ]
